# Generated by Django 3.2.7 on 2021-12-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolesDeProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(max_length=100)),
                ('defecto', models.BooleanField(default=True)),
                ('permisos', models.ManyToManyField(blank=True, to='auth.Permission')),
            ],
            options={
                'permissions': [('pp_proyecto', 'Administrar_proyecto'), ('pp_proyecto_integrantes', 'Administrar miembros del proyecto'), ('pp_roles_proyecto', 'Administrar roles de proyecto'), ('pp_administrar_us', 'Administrar User story'), ('pp_sprint', 'Administrar Sprint'), ('pp_developer', 'Administrar team developer'), ('pp_moverUS', 'Mover US en el Kanban'), ('pp_US_QA', 'Mover US a QA'), ('pp_product_backlog', 'administrar product backlog'), ('pp_sprint_backlog', ' Administrar sprint backlog'), ('pp_bchart', 'Administrar burndown chart'), ('pp_verproyecto', 'Vista para invitado')],
            },
        ),
    ]
