# Generated by Django 3.2.7 on 2021-12-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RolesdeProyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolesdeproyecto',
            options={'permissions': [('pp_proyecto', 'Administrar proyectos'), ('pp_roles', 'Administrar roles'), ('pp_miembros_proyecto', 'Administrar miembros del proyecto'), ('pp_roles_scrum', 'Administrar  de roles'), ('pp_sprint', 'Administrar Sprint'), ('pp_developer', 'Administrar team developer'), ('pp_us', 'Administrar user story'), ('pp_product_backlog', 'Administrar product backlog'), ('pp_sb', 'Administrar sprint backlog'), ('pp_us_asignado', 'Administrar user story asignado'), ('pp_kanban', 'Desplazar US en el tablero Kanban'), ('pp_kanban_qa', 'Mover US a QA'), ('pp_burndownchart', 'Cargar horas de trabajo')]},
        ),
        migrations.RemoveField(
            model_name='rolesdeproyecto',
            name='defecto',
        ),
        migrations.AlterField(
            model_name='rolesdeproyecto',
            name='descripcion',
            field=models.TextField(blank=True, max_length=60),
        ),
    ]
