# Generated by Django 3.2.7 on 2021-12-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolesdeSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True, max_length=60)),
                ('permisos', models.ManyToManyField(blank=True, to='auth.Permission')),
            ],
            options={
                'permissions': [('ps_usuarios', 'Administrar usuarios en el sitema'), ('ps_proyectos', 'Administrar proyectos e integrantes'), ('ps_roles', 'Administrar creacion de role en el sistema')],
            },
        ),
    ]
